fix CONFIG_MTK_SCHED_EXTENSION
../kernel/sched/fair.c:9022:3: error: use of undeclared identifier 'load'
                load  += mt_rt_load(i);
                ^
../kernel/sched/fair.c:9565:3: error: use of undeclared identifier 'wl'
                wl += mt_rt_load(i);
                ^
2 errors generated.

../drivers/misc/mediatek/met_drv_v2/Makefile:42: Not building met.ko due to CONFIG_MODULES is not set, build met default
In file included from ../drivers/misc/mediatek/performance/boost_ctrl/topo_ctrl/topo_ctrl.c:13:
../kernel/sched/sched.h:2924:20: error: static declaration of 'check_for_migration' follows non-static declaration
static inline void check_for_migration(struct rq *rq, struct task_struct *p) { }
                   ^
../kernel/sched/extension/eas_plus.h:115:13: note: previous declaration is here
extern void check_for_migration(struct task_struct *p);
            ^
In file included from ../drivers/misc/mediatek/performance/boost_ctrl/topo_ctrl/topo_ctrl.c:13:
../kernel/sched/sched.h:2953:20: error: static declaration of 'is_max_capacity_cpu' follows non-static declaration
static inline bool is_max_capacity_cpu(int cpu) { return true; }
                   ^
../kernel/sched/extension/eas_plus.h:118:13: note: previous declaration is here
extern bool is_max_capacity_cpu(int cpu);
            ^
In file included from ../drivers/misc/mediatek/performance/boost_ctrl/topo_ctrl/topo_ctrl.c:13:
../kernel/sched/sched.h:2954:20: error: static declaration of 'is_min_capacity_cpu' follows non-static declaration
static inline bool is_min_capacity_cpu(int cpu) { return true; }
                   ^
../kernel/sched/extension/eas_plus.h:117:13: note: previous declaration is here
extern bool is_min_capacity_cpu(int cpu);
            ^
In file included from ../drivers/misc/mediatek/performance/boost_ctrl/topo_ctrl/topo_ctrl.c:13:
../kernel/sched/sched.h:3023:19: error: static declaration of 'is_reserved' follows non-static declaration
static inline int is_reserved(int cpu)
                  ^
../kernel/sched/extension/eas_plus.h:116:12: note: previous declaration is here
extern int is_reserved(int cpu);
           ^
4 errors generated.